// Copyright (c) 2021 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:projectid: graphql-intro
:page-layout: guide-multipane
:page-duration: 25 minutes
:page-releasedate: 2021-01-29
:page-essential: false
:page-description: Learn how to create and test a GraphQL service using MicroProfile GraphQL and Open Liberty.
:page-tags: ['MicroProfile', 'Java EE', 'Jakarta EE']
:page-related-guides: ['rest-intro', 'jpa-intro', 'mongodb-intro']
:page-permalink: /guides/{projectid}
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/master
:source-highlighter: prettify
:page-seo-title: Accessing and manipulating data using Microprofile GraphQL in Open Liberty
:page-seo-description: Learn how to create an application that manipulates and returns data using the GraphQL query language implemented through Microprofile GraphQL
:guide-author: Open Liberty
= Accessing and manipulating data with GraphQL

[.hidden]
NOTE: This repository contains the guide documentation source. To view the guide in published form,
view it on the https://openliberty.io/guides/{projectid}.html[Open Liberty website].

Explore how to use GraphQL to access and manipulate data using Microprofile GraphQL on Open Liberty

== What you'll learn

You will learn how to build and test a simple GraphQL service with Microprofile GraphQL. 

GraphQL is an open source data query and manipulation language. 
Unlike REST APIs, `POST` requests going to a GraphQL service all go to a single endpoint.
Operations and their details are differentiated by the contents of the `POST` request.
If the operation returns data, the user will also specify what properties of the data they want returned. 
A JSON object is returned, containing only the data and properties specified.

This is beneficial when dealing with large resources or ones that contain properties that are expensive to calculate. 
By returning only the requested properties, GraphQL reduces the size of the responses. 
For resources that contain properties that are expensive to calculate, such as other nested resources, 
GraphQL reduces processing time by only calculating them if requested. 

You can learn more about GraphQL at https://graphql.org/[the GraphQL website^].

The service you'll create will respond to `POST` requests made to the `\http://localhost:9080/graphql` URL. 
The operations you'll implement will be a simple `query` operation and a `mutation` operation.
The `query` operation will return system information.
The `mutation` operation will save a note of your choice into the system information. 

Manual testing of the application will be done using GraphiQL, which is included in the project.
GraphiQL is a webpage that allows you to easily make `POST` requests to the GraphQL service and see the responses.
In GraphiQL you only need to type the body of the `POST` request, streamlining manual tests. 
You're also able to view a history of your previous requests and repeat any of them.

For more, check out https://github.com/graphql/graphiql/tree/main/packages/graphiql[GraphiQL on Github^].

///////////////////////////
// Getting started
///////////////////////////

[role='command']
include::{common-includes}/gitclone.adoc[]

///////////////////////////
// Try what you'll build
///////////////////////////
[role='command']
include::{common-includes}/twyb-intro.adoc[]

Access the application through GraphiQL at the http://localhost:9080/graphiql.html[^] URL.

Enter the following `query` operation into the input box on the left. 

[role='command']
----
query {
  system {
    username
  }
}
----

Press `CTRL+enter` to run your `query` operation. 
The output will appear in the text box on the right, and will be similar to the following:

[role='no_copy']
----
{
  "data": {
    "system": {
      "username": "admin"
    }
  }
}
----

[role='command']
include::{common-includes}/twyb-end.adoc[]

== Creating GraphQL object types

Navigate to the `start` directory to begin.

[role='command']
include::{common-includes}/devmode-lmp33-start.adoc[]

You'll create three object types to define the structure of the data returned by GraphQL.
You'll apply various annotations to the properties and declaration of a Java class to define an object type.

[role="code_command hotspot file=0", subs="quotes"]
----
#Create the `JavaInfo` class.#
`src/main/java/io/openliberty/guides/graphql/models/JavaInfo.java`
----

The [hotspot=class file=0]`JavaInfo` class is annotated with an `@Type` annotation. 
The [hotspot=type file=0]`@Type("java")` annotation maps this class to define the `java` object type in GraphQL.
The `java` object type will give information on the system's Java installation. 

The [hotspot=description file=0]`@Description` annotation gives a description to the `java` object type in GraphQL.
This description is what will appear in the schema and the documentation. 

The [hotspot=name1 hotspot=name2 file=0]`@Name` annotations map their respective properties to properties of the `java` object type in GraphQL. 
All data types in GraphQL are nullable by default.
Non-nullable properties are annotated with the [hotspot=nonnull file=0]`@NonNull` annotation.
The [hotspot=getVendor file=0]`getVendor()` and [hotspot=getVersion file=0]`getVersion()` getter functions will automatically be mapped to retrieve their respective properties in GraphQL. 
If needed, setter functions are also supported and will be automatically mapped. 

[role="code_command hotspot file=1" ,subs="quotes"]
----
#Create the `OperatingSystem` class.#
`src/main/java/io/openliberty/guides/graphql/models/OperatingSystem.java`
----

The [hotspot=class file=1]`OperatingSystem` class is set up similarly.
It maps to the [hotspot=type file=1]`operatingSystem` object type, which describes the operating system's information. 

[role="code_command hotspot file=2" ,subs="quotes"]
----
#Create the `SystemInfo` class.#
`src/main/java/io/openliberty/guides/graphql/models/SystemInfo.java`
----

The [hotspot=class file=2]`SystemInfo` class is similar to the previous two files. 
It maps to the [hotspot=type file=2]`system` object type, which describes other information Java can retrieve from the system properties.

The `java` and `operatingSystem` object types will be used as nested objects within the `system` object type.
However, nested objects and other properties that are expensive to calculate or retrieve are not included in an object type's class. 
Instead, expensive properties are added as part of implementing GraphQL resolvers. 

// file 0
JavaInfo.java
[source, java, linenums, role='code_column hide_tags=copyright']
----
include::finish/src/main/java/io/openliberty/guides/graphql/models/JavaInfo.java[]
----

// file 1
OperatingSystem.java
[source, java, linenums, role='code_column hide_tags=copyright']
----
include::finish/src/main/java/io/openliberty/guides/graphql/models/OperatingSystem.java[]
----

// file 2
SystemInfo.java
[source, java, linenums, role='code_column hide_tags=copyright']
----
include::finish/src/main/java/io/openliberty/guides/graphql/models/SystemInfo.java[]
----

== Implementing GraphQL resolvers

Resolvers are functions that provide instructions for GraphQL operations.
We'll implement resolvers for the `query` and `mutation` operation types.
The `query` operation type is read-only and fetches data.
The `mutation` operation type can create, delete, or modify data. 

[role="code_command hotspot file=0" ,subs="quotes"]
----
#Create the `SystemResource` class.#
`src/main/java/io/openliberty/guides/graphql/SystemResource.java`
----

The resolvers are defined in the [hotspot file=0]`SystemResource.java` file.
The [hotspot=graphqlapi file=0]`@GraphQLApi` annotation makes it so that GraphQL will use the methods defined in this class as resolvers. 

The [hotspot=query file=0]`@Query` annotation maps functions to operations of the `query` type.
Here the [hotspot=query file=0]`@Query` annotation maps the [hotspot=getSystemInfo file=0]`getSystemInfo()` function to handling `system` requests, retrieving the system information. 

The [hotspot=mutation file=0]`@Mutation` annotation maps functions to operations of the `mutation` type.
Here the [hotspot=mutation file=0]`@Mutation` annotation maps the [hotspot=editNoteFunction file=0]`editNote()` function to handling `editNote` operations. 
The [hotspot=editNoteHeader file=0]`@Name` annotation in this context denotes what inputs will be used for the operation.
Here, there's just one input `note` for the note to write into the system properties.

Each resolver function has an [hotspot=description1 hotspot=description2 file=0]`@Description` annotation, which provides a description to be used for the schema. 

The [hotspot=operatingSystemHeader hotspot=javaHeader file=0]`@Source` annotation is used to add properties to object types. 
Here the [hotspot=operatingSystemHeader hotspot=javaHeader file=0]`@Source` annotation adds [hotspot=javaFunction file=0]`java` 
and [hotspot=os file=0]`operatingSystem` object types as properties of the `system` object type.
The [hotspot=operatingSystemHeader hotspot=javaHeader file=0]`@Source` annotation is used for any properties that are expensive to calculate or look up.
These properties will only be calculated or looked up if requested, saving server time and resources.

// file 0
SystemResource.java
[source, java, linenums, role='code_column hide_tags=copyright']
----
include::finish/src/main/java/io/openliberty/guides/graphql/SystemResource.java[]
----

== Enabling GraphQL

To use GraphQL, the Microprofile GraphQL dependencies and features need to be included. 

[role="code_command hotspot file=0" ,subs="quotes"]
----
#Replace the Maven project file.#
`pom.xml`
----

Adding the [hotspot=graphQLDependency file=0]`microprofile-graphql-api` dependency to the [hotspot file=0]`pom.xml` 
enables the GraphQL annotations used to develop the application. 

The Open Liberty server needs to be configured to support the GraphQL query language. 

[role="code_command hotspot file=1" ,subs="quotes"]
----
#Replace the server configuration file.#
`src/main/liberty/config/server.xml`
----

The https://openliberty.io/docs/20.0.0.12/reference/feature/mpGraphQL-1.0.html[MicroProfile GraphQL^] ([hotspot=graphql file=1]`mpGraphQL-1.0`) feature
added to the [hotspot file=1]`server.xml` enables the use of the GraphQL feature in OpenLiberty.

// file 0
pom.xml
[source, xml, linenums, role='code_column hide_tags=copyright']
----
include::finish/pom.xml[]
----

// file 1
server.xml
[source, xml, linenums, role='code_column hide_tags=copyright']
----
include::finish/src/main/liberty/config/server.xml[]
----

///////////////////////////
// Running the application
///////////////////////////

[role='command']
include::{common-includes}/devmode-build.adoc[]

GraphiQL has already been set up and included for you.
Access GraphiQL at the http://localhost:9080/graphiql.html[^] URL.
Queries made through GraphiQL will be the same as queries made through `POST` requests. 

In GraphiQL, you can view the application documentation by clicking `Docs`. 
The documentation will describe the GraphQL schema.
The schema gives details on the various operations available and descriptions of them. 
If any data types are mentioned, you'll also be able to see descriptions of them and the fields contained within them if applicable. 
The schema will also be visible at the http://localhost:9080/graphql/schema.graphql[^] URL. 

Run the following `query` operation to get every system property by entering it into GraphiQL. 

[role='command']
----
query {
  system {
    java { vendor version }
    operatingSystem { arch version name }
    username
    timezone
  }
}
----

The output will be similar to the following:

[role='no_copy']
----
{
  "data": {
    "system": {
      "java": {
        "vendor": "Oracle Corporation",
        "version": "11.0.7"
      },
      "operatingSystem": {
        "arch": "x86_64",
        "version": "10.15.6",
        "name": "Mac OS X"
      },
      "username": "admin",
      "timezone": "America/Toronto"
    }
  }
}
----
Run the following mutation operation to add a note to the system.

[role='command']
----
mutation {
  editNote(note: "I'm trying out GraphQL on OpenLiberty!")
}
----

You'll receive a response containing the boolean `true` to let you know that the request was successfully processed.
You can see the note you added by running the following query operation.

[role='command']
----
query {
  system {
    note
  }
}
----

The response will be similar to the following:

[role='no_copy']
----
{
  "data": {
    "system": {
      "note": "I'm trying out GraphQL on OpenLiberty!"
    }
  }
}
----

Notice that this time, only the `note` property is returned, as it was the only property in the request. 

== Testing the application

Manual tests can be done using GraphiQL at the http://localhost:9080/graphiql.html[^] URL. 
However, automated tests are a better approach because they trigger a failure if a change introduces a bug.

We'll write tests using JUnit to call the application server directly. 

[role="code_command hotspot file=0" ,subs="quotes"]
----
#Create the `SystemIT` class.#
`src/test/java/io/openliberty/guides/graphql/SystemIT.java`
----

The [hotspot file=0]`SystemIT` class contains our test methods.

Each test is annotated with the [hotspot=test1 hotspot=test2 file=0]`@Test` annotation. 

The [hotspot=testGet file=0]`testGetSystem()` method makes a query using the `system` resolver through a `POST` request.
It then verifies that the response is not empty and that it's free of errors. 

The [hotspot=testEdit file=0]`testEditNote()` method makes a query using the `editNote` resolver.
It will try to set the note to be the current system time. 
Then, it makes a query using the `system` resolver to ensure the note was saved correctly. 

// file 0
SystemIT.java
[source, java, linenums, role='code_column hide_tags=copyright']
----
include::finish/src/test/java/io/openliberty/guides/graphql/SystemIT.java[]
----

// Running the tests

[role=command]
include::{common-includes}/devmode-test.adoc[]

You will see the following output:

[source,role="no_copy"]
----
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.008 s - in io.openliberty.guides.graphql.SystemIT

Results:

Tests run: 2, Failures: 0, Errors: 0, Skipped: 0
----

[role=command]
include::{common-includes}/devmode-quit.adoc[]

== Great work! You're done!

You just created a basic GraphQL service using Microprofile GraphQL in Open Liberty!

include::{common-includes}/attribution.adoc[]

// ------------ END ------------
