// Copyright (c) 2020 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:projectid: graphql-intro
:page-layout: guide-multipane
:page-duration: 25 minutes
:page-releasedate: 2020-12-21
:page-essential: false
:page-description: Learn how to create and test a GraphQL service using MicroProfile GraphQL and Open Liberty.
:page-tags: ['MicroProfile', 'Java EE', 'Jakarta EE']
:page-related-guides: ['rest-intro']
:page-permalink: /guides/{projectid}
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/master
:source-highlighter: prettify
:page-seo-title: Creating a GraphQL service using Microprofile GraphQL
:page-seo-description: Find out how to create and test a GraphQL service on Open Liberty using Microprofile GraphQL
:guide-author: Open Liberty
= Creating and consuming a GraphQL microservice

[.hidden]
NOTE: This repository contains the guide documentation source. To view the guide in published form,
view it on the https://openliberty.io/guides/{projectid}.html[Open Liberty website].

Explore how to create a GraphQL service using Microprofile GraphQL on Open Liberty

== What you'll learn

You will learn how to build and test a simple GraphQL service with Microprofile GraphQL. 
The service will respond to `POST` requests made to the `http://localhost:9080/graphql` URL. 
The `POST` requests will contain a query with a requested resource and a list of properties within that resource.
GraphQL will respond with the desired resource and only the properties listed. 

This is beneficial when dealing with large resources or ones which contain properties that are expensive to calculate. 
By returning only the requested properties, GraphQL reduces the size of the responses. 
For resources that contain properties that are expensive to calculate such as other nested resources, GraphQL reduces processing time by only calculating them if requested. 

Unlike REST services, all GraphQL requests go to the same endpoint. 
Requests are differentiated by the contents of the request rather than the endpoint, which can simplify your application. 

You can learn more about GraphQL by visiting https://graphql.org/[their webpage^].

///////////////////////////
// Getting started
///////////////////////////

[role='command']
include::{common-includes}/gitclone.adoc[]

[role='command']
include::{common-includes}/twyb-intro.adoc[]

Included with the application is a service called GraphiQL. 
GraphiQL is a webpage served by the Open Liberty server and can be used to assist in development and testing of the service.
GraphiQL allows you to easily make `POST` requests to the GraphQL service and see the responses.

Once the server is running, access the schema at the http://localhost:9080/graphql/schema.graphql[^] URL. 
The schema informs you of the queries available in the service as well as the possible resources that can be retrieved. 
Open GraphiQL at the http://localhost:9080/graphiql.html[^] URL. 
Run the following `query` command in GraphiQL to get every property available. 

[role='command']
----
query {
  system {
    java {
      vendor
      version
    }
    operatingSystem {
      arch
      version
      name
    }
    username
    timezone
  }
}
----

The output will be similar to the following:

[role='no_copy']
----
{
  "data": {
    "system": {
      "java": {
        "vendor": "Oracle Corporation",
        "version": "13.0.2"
      },
      "operatingSystem": {
        "arch": "x86_64",
        "version": "10.15.6",
        "name": "Mac OS X"
      },
      "username": "admin",
      "timezone": "America/Toronto"
    }
  }
}
----

Run the following `mutation` command to add a note to the system.

[role='command']
----
mutation {
  editNote(note:"I am trying out GraphQL on OpenLiberty!")
}
----

You will receive a response containing the boolean `true` to notify you that the request was processed.
You can see the note you added by running the following query.

[role='command']
----
query {
  system {
    note
  }
}
----

The response will be similar to the following:

[role='no_copy']
----
{
  "data": {
    "system": {
      "note": "I am trying out GraphQL on OpenLiberty!"
    }
  }
}
----

Notice that this time, only the `note` property is returned, as it was the only property in the `query` request. 

[role='command']
include::{common-includes}/twyb-end.adoc[]

== Building the application

Navigate to the `start` directory

[role='command']
include::{common-includes}/devmode-start.adoc[]

== Enabling GraphQL

[role="code_command hotspot" ,subs="quotes"]
----
#Replace the `server.xml` file.#
`src/main/liberty/config/server.xml`
----

[role="code_command hotspot" ,subs="quotes"]
----
#Replace the `pom.xml` file.#
`pom.xml`
----

Adding the [hotspot=graphql file=0]`mpGraphQL` feature to the [hotspot file=0]`server.xml` 
and the [hotspot=graphQLDependency file=1]`microprofile-graphql-api` dependency to the [hotspot file=1]`pom.xml` 
enables the GraphQL runtime and use of GraphQL API for your application. 

// file 0
server.xml
[source, xml, linenums, role='code_column hide_tags=copyright']
----
include::finish/src/main/liberty/config/server.xml[]
----

// file 1
pom.xml
[source, xml, linenums, role='code_column hide_tags=copyright']
----
include::finish/pom.xml[]
----

== Creating GraphQL resources

In GraphQL resources are defined using Java classes. 
Each resource should have a single Java class describing it. 
Annotations are used to denote which properties and methods GraphQL should use.

The first class we will create will describe the operating system installed on the machine. 

[role="code_command hotspot file=0", subs="quotes"]
----
#Create the `OperatingSystem` class.#
`src/main/java/io/openliberty/guides/graphql/models/OperatingSystem.java`
----

The [hotspot=type file=0]`@Type` annotation maps the `OperatingSystem` class to a GraphQL resource of the same name. 

The [hotspot=description file=0]`@Description` annotation gives the `OperatingSystem` resource a description in the GraphQL schema. 

The [hotspot=nonnull1 hotspot=nonnull2 hotspot=nonnull3 file=0]`@NonNull` annotation marks properties as non-nullable.
This means that if these properties are requested, GraphQL guarantees the properties will not be `null`. 
Data types that are primitives such as `int` do not need the `@NonNull` annotation.
GraphQL will automatically mark such properties as non-nullable. 

The [hotspot=name1 hotspot=name2 hotspot=name3 file=0]`@Name` annotation specifies what the name of the property will be in GraphQL.
This can be different from the name of the variable in the Java class. 

The `@NonNull` and `@Name` annotations can be placed on either the properties themselves or its getters and setters.
If applied on only the getter or setter, they will only affect those operations. 
If applied on the property, the annotation will apply to both the getter and setter if applicable. 
In this example, the annotations are applied to properties. 

[role="code_command hotspot file=1", subs="quotes"]
----
#Create the `JavaInfo` class.#
`src/main/java/io/openliberty/guides/graphql/models/JavaInfo.java`
----

[role="code_command hotspot file=2", subs="quotes"]
----
#Create the `SystemInfo` class.#
`src/main/java/io/openliberty/guides/graphql/models/SystemInfo.java`
----

The [hotspot file=1]`JavaInfo` and [hotspot file=2]`SystemInfo` classes are similar to the `OperatingSystem` class. 
`JavaInfo` describes the Java installation on the machine. 
`SystemInfo` describes general system information. 

// file 0
OperatingSystem.java
[source, Java, linenums, role='code_column hide_tags=copyright']
----
include::finish/src/main/java/io/openliberty/guides/graphql/models/OperatingSystem.java[]
----

// file 1
JavaInfo.java
[source, Java, linenums, role='code_column hide_tags=copyright']
----
include::finish/src/main/java/io/openliberty/guides/graphql/models/JavaInfo.java[]
----

// file 2
SystemInfo.java
[source, Java, linenums, role='code_column hide_tags=copyright']
----
include::finish/src/main/java/io/openliberty/guides/graphql/models/SystemInfo.java[]
----

== Creating the GraphQL API

GraphQL has two kinds of operations.

`Query` operations retrieve data from the service.
`Mutation` operations modify data in the service.
This includes inserting data and modifying already existing data. 

All operations are defined with methods in a Java class.

[role="code_command hotspot", subs="quotes"]
----
#Create the `SystemResource` class.#
`src/main/java/io/openliberty/guides/graphql/SystemResource.java`
----

The [hotspot=graphqlapi]`@GraphQLApi` annotation means GraphQL will use the methods defined in this class. 

The [hotspot=nonnull1 hotspot=nonnull2 hotspot=nonnull3]`@NonNull` and [hotspot=description1 hotspot=description2]`@Description` annotations
act similarly to how they act when defining models.

The [hotspot=query]`@Query` annotation maps the `getSystemInfo()` method to the `system` query operation in GraphQL. 

The [hotspot=mutation]`@Mutation` annotation maps the `editNote()` method to the `editNote` mutation operation in GraphQL. 

The [hotspot=editNoteHeader]`@Name` annotation here names an input for an operation. 

The [hotspot=operatingSystemHeader hotspot=javaHeader]`@Source` annotation is used for creating more complex objects.
The `@Source` annotation adds to the resource defined by the `SystemInfo` class. 
Here it adds the `JavaInfo` and `OperatingSystem` classes as fields to the resource. 
These fields are more expensive to calculate so the code in these methods would only be run if these fields are requested. 

SystemResource.java
[source, Java, linenums, role='code_column hide_tags=copyright']
----
include::finish/src/main/java/io/openliberty/guides/graphql/SystemResource.java[]
----

///////////////////////////
// Running the application
///////////////////////////

[role='command']
include::{common-includes}/devmode-build.adoc[]

Access GraphiQL at the http://localhost:9080/graphiql.html[^] URL. 
View your GraphQL schema at the http://localhost:9080/graphql/schema.graphql[^] URL. 

== Testing the application

Manual tests can be done using GraphiQL, but automated tests are a better approach because they trigger a failure if a change introduces a bug.

In this example we will write tests to call the application server directly. 
We will use the SmallRye GraphQL client added in [hotspot=smallrye file=0]`pom.xml` to automatically make calls to our service. 

[role="code_command hotspot", subs="quotes"]
----
#Create the `SystemServiceAPI` interface.#
`src/test/java/io/openliberty/guides/graphql/client/SystemServiceAPI.java`
----

The [hotspot=graphQLClientApi file=1]`@GraphQlClientApi` annotation marks this interface for use as a GraphQL client.

The [hotspot=query file=1]`@Query` and [hotspot=mutation file=1]`@Mutation` annotations map these functions to the specified query and mutation operations in the GraphQL service. 

The [hotspot=editNote file=1]`@Name` annotation maps the parameter of the function to a parameter of the mutation operation. 

// file 0
pom.xml
[source, xml, linenums, role='code_column hide_tags=copyright']
----
include::finish/pom.xml[]
----

// file 1
SystemServiceAPI.java
[source, Java, linenums, role='code_column hide_tags=copyright']
----
include::finish/src/test/java/io/openliberty/guides/graphql/client/SystemServiceAPI.java[]
----

[role='command']
include::{common-includes}/devmode-test.adoc[]

== Great work! You're done!

You just created a basic GraphQL service using Microprofile GraphQL in Open Liberty!

include::{common-includes}/attribution.adoc[]

// ------------ END ------------