// Copyright (c) 2021 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:projectid: graphql-intro
:page-layout: guide-multipane
:page-duration: 25 minutes
:page-releasedate: 2021-05-28
:page-essential: false
:page-description: Learn how to create and test a GraphQL service using MicroProfile GraphQL and Open Liberty.
:page-tags: ['MicroProfile', 'Jakarta EE']
:page-related-guides: ['rest-intro', 'jpa-intro', 'mongodb-intro']
:page-permalink: /guides/{projectid}
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/master
:source-highlighter: prettify
:page-seo-title: Accessing and manipulating data using MicroProfile GraphQL in Open Liberty
:page-seo-description: Learn how to create an application that manipulates and returns data using the GraphQL query language implemented through MicroProfile GraphQL
:guide-author: Open Liberty
= Accessing and manipulating data with GraphQL

[.hidden]
NOTE: This repository contains the guide documentation source. To view the guide in published form,
view it on the https://openliberty.io/guides/{projectid}.html[Open Liberty website].

Explore how to use GraphQL to access and manipulate data using MicroProfile GraphQL on Open Liberty

== What you'll learn

You will learn how to build and use a simple GraphQL service with 
https://openliberty.io/docs/latest/reference/feature/mpGraphQL-1.0.html[MicroProfile GraphQL^]. 

GraphQL is an open source data query language. 
Unlike REST APIs, each `POST` request that is sent to a GraphQL service goes to a single HTTP endpoint. 
Create, read, update, and delete (CRUD) operations and their details are differentiated by the contents of the request.
If the operation returns data, the user specifies what properties of the data that they want returned. 
For read operations, a JSON object is returned that contains only the data and properties that are specified.
For other operations, a JSON object might be returned containing information such as a success message. 

Returning only the specified properties in a read operation has two benefits.
It reduces the size of the responses if you're dealing with large amounts of data or large resources.
It also saves processing time if you have properties that are expensive to calculate or retrieve such as nested resources.
GraphQL will only get these properties if they are requested.

You can learn more about GraphQL at the https://graphql.org/[GraphQL website^].

You'll create two services.
The `backend` service will be a GraphQL service that responds to requests made to the `\http://localhost:9080/graphql` URL. 
The `system` service will make requests to the `backend` service and display the data using OpenAPI.
To learn more about OpenAPI, check out our 
https://openliberty.io/guides/microprofile-openapi.html[Documenting RESTful APIs] guide.

The guide also includes https://github.com/graphql/graphiql/tree/main/packages/graphiql[GraphiQL^].
GraphiQL assists in manually making `POST` requests to a GraphQL service.
In GraphiQL you need to type only the body of the request for the purposes of manual tests and examples. 

///////////////////////////
// Getting started
///////////////////////////

[role='command']
include::{common-includes}/gitclone.adoc[]

// No "Try what you'll build" because of multiple services, will take too long

== Creating GraphQL object types

Navigate to the `start` directory to begin.

Object types define the structure of the data returned by GraphQL. 
Annotations that are applied to the declaration and properties of Java classes define object types.

[role="code_command hotspot file=0", subs="quotes"]
----
#Create the `JavaInfo` class.#
`models/src/main/java/io/openliberty/guides/graphql/models/JavaInfo.java`
----

The [hotspot=class file=0]`JavaInfo` class is annotated with an `@Type` annotation. 
The [hotspot=type file=0]`@Type("java")` annotation maps this class to define the `java` object type in GraphQL.
The `java` object type gives information on the Java installation of the system. 

The [hotspot=description file=0]`@Description` annotation gives a description to the `java` object type in GraphQL.
This description is what appears in the schema and the documentation. 
Descriptions aren't required, but it's good practice to include them. 

The [hotspot=name file=0]`@Name` annotation maps the `vendor` property to the `vendorName` property of the `java` object type in GraphQL. 
The [hotspot=name file=0]`@Name` annotation is used when mapping a property in a Java object to a property of a different name in the GraphQL object type.
Without an [hotspot=name file=0]`@Name` annotation, the Java object property is automatically 
mapped to a GraphQL object type property of the same name. 

All data types in GraphQL are nullable by default.
Non-nullable properties are annotated with the [hotspot=nonnull file=0]`@NonNull` annotation.
The [hotspot=getVendor file=0]`getVendor()` and [hotspot=getVersion file=0]`getVersion()` getter functions 
are automatically mapped to retrieve their respective properties in GraphQL. 
If needed, setter functions are also supported and automatically mapped. 

[role="code_command hotspot file=1" ,subs="quotes"]
----
#Create the `OperatingSystem` class.#
`src/main/java/io/openliberty/guides/graphql/models/OperatingSystem.java`
----

The [hotspot=class file=1]`OperatingSystem` class is set up similarly.
It maps to the [hotspot=type file=1]`operatingSystem` object type, which describes the operating system's information. 

[role="code_command hotspot file=2" ,subs="quotes"]
----
#Create the `SystemInfo` class.#
`src/main/java/io/openliberty/guides/graphql/models/SystemInfo.java`
----

The [hotspot=class file=2]`SystemInfo` class is similar to the previous two files. 
It maps to the [hotspot=type file=2]`system` object type, which describes other information Java can retrieve from the system properties.

The `java` and `operatingSystem` object types are used as nested objects within the `system` object type.
However, nested objects and other properties that are expensive to calculate or retrieve are not included in the class of an object type.
Instead, expensive properties are added as part of implementing GraphQL resolvers. 

Run `mvn install` to compile and install the object types.

[role='command']
```
mvn -pl models install
```

// file 0
JavaInfo.java
[source, java, linenums, role='code_column hide_tags=copyright']
----
include::finish/models/src/main/java/io/openliberty/guides/graphql/models/JavaInfo.java[]
----

// file 1
OperatingSystem.java
[source, java, linenums, role='code_column hide_tags=copyright']
----
include::finish/models/src/main/java/io/openliberty/guides/graphql/models/OperatingSystem.java[]
----

// file 2
SystemInfo.java
[source, java, linenums, role='code_column hide_tags=copyright']
----
include::finish/models/src/main/java/io/openliberty/guides/graphql/models/SystemInfo.java[]
----

== Implementing GraphQL resolvers

Resolvers are functions that provide instructions for GraphQL operations.
Each operation requires a corresponding resolver.
The `query` operation type is read-only and fetches data.
The `mutation` operation type can create, delete, or modify data. 

[role="code_command hotspot file=0" ,subs="quotes"]
----
#Create the `SystemGraphQLResource` class.#
`backend/src/main/java/io/openliberty/guides/backend/SystemGraphQLService.java`
----

The resolvers are defined in the [hotspot file=0]`SystemGraphQLResource.java` file.
The [hotspot=graphqlapi file=0]`@GraphQLApi` annotation enables GraphQL to use the methods that are defined in this class as resolvers. 

Operations of the `query` type are read-only operations that retrieve data.
They are defined by using the [hotspot=query1 hotspot=query2 file=0]`@Query` annotation.
Two functions are defined and mapped to `query` operations.

The [hotspot=getSystemInfo file=0]`getSystemInfo()` function handles `system` requests.
It retrieves and bundles system information into a `SystemInfo` object type that is returned.

The [hotspot=getProperty file=0]`getProperty()` function handles `property` requests.
In this context, the [hotspot=getPropertyHeader file=0]`@Name` annotation denotes an input for this operation.
The `name` input is used in this operation to retrieve a single system property and return it. 

The [hotspot=mutation file=0]`@Mutation` annotation maps functions to operations of the `mutation` type.
Operations of the `mutation` type modify data.
They create, update, or delete data. 
A single function is defined and mapped to a `mutation` operation.

The [hotspot=editNoteFunction file=0]`editNote()` function handles `editNote` operations.
An [hotspot=editNoteHeader file=0]`@Name` annotation denotes a `note` input, 
which specifies the note that is written into the system properties.

Each resolver function has an [hotspot=description1 hotspot=description2 hotspot=description3 file=0]`@Description` 
annotation, which provides a description to be used for the schema. 
Descriptions aren't required, but it's good practice to include them. 

The [hotspot=operatingSystemHeader hotspot=javaHeader file=0]`@Source` annotation is used to add properties to object types. 
This annotation adds [hotspot=javaFunction file=0]`java` 
and [hotspot=os file=0]`operatingSystem` object types as properties of the `system` object type.
The [hotspot=operatingSystemHeader hotspot=javaHeader file=0]`@Source` annotation is used for any properties that are expensive to calculate or search for.
These properties are calculated or searched for only if requested, which saves time and resources.

// file 0
SystemResource.java
[source, java, linenums, role='code_column hide_tags=copyright']
----
include::finish/backend/src/main/java/io/openliberty/guides/backend/SystemGraphQLService.java[]
----

== Enabling GraphQL

To use GraphQL, the MicroProfile GraphQL dependencies and features need to be included. 

[role="code_command hotspot file=0" ,subs="quotes"]
----
#Replace the Maven project file.#
`backend/pom.xml`
----

Adding the [hotspot=graphQLDependency file=0]`microprofile-graphql-api` dependency to the [hotspot file=0]`pom.xml` 
enables the GraphQL annotations that are used to develop the application. 

The Open Liberty server needs to be configured to support the GraphQL query language. 

[role="code_command hotspot file=1" ,subs="quotes"]
----
#Replace the server configuration file.#
`backend/src/main/liberty/config/server.xml`
----

The https://openliberty.io/docs/latest/reference/feature/mpGraphQL-1.0.html[MicroProfile GraphQL^] ([hotspot=graphql file=1]`mpGraphQL-1.0`) feature
that is added to the [hotspot file=1]`server.xml` enables the use of the GraphQL feature in OpenLiberty.

// file 0
pom.xml
[source, xml, linenums, role='code_column hide_tags=copyright']
----
include::finish/backend/pom.xml[]
----

// file 1
server.xml
[source, xml, linenums, role='code_column hide_tags=copyright']
----
include::finish/backend/src/main/liberty/config/server.xml[]
----

== Running the GraphQL service

Run the followinig commands to start the `backend` service: 

[role='command']
----
mvn -pl backend package
mvn -pl backend liberty:run
----

After you see the following message, the `backend` service is ready:

[role="no_copy"]
----
The defaultServer server is ready to run a smarter planet.
----

A GraphQL service is described by a schema. 
The schema is visible at the http://localhost:9080/graphql/schema.graphql[^] URL. 
The schema details what operations are available as well as any object types that are returned.
Object types described will have their fields and their types listed. 
If defined, descriptions of object types and operations will also be included.

To access the `backend` service, GraphiQL has already been set up and included for you.
Access GraphiQL at the http://localhost:9080/graphiql.html[^] URL.
Queries that are made through GraphiQL are the same as queries that are made through HTTP requests. 
You can also view the schema through GraphiQL by clicking the `Docs` button on the menu bar. 

Run the following `query` operation in GraphiQL to get every system property. 

[role='command']
----
query {
  system {
    java { vendorName version }
    operatingSystem { arch version name }
    username
    timezone
  }
}
----

The output is similar to the following example:

[role='no_copy']
----
{
  "data": {
    "system": {
      "java": {
        "vendorName": "AdoptOpenJDK",
        "version": "11.0.7"
      },
      "operatingSystem": {
        "arch": "x86_64",
        "version": "10.15.7",
        "name": "Mac OS X"
      },
      "username": "admin",
      "timezone": "America/Toronto"
    }
  }
}
----
Run the following mutation operation to add a note to the system.

[role='command']
----
mutation {
  editNote(note: "I'm trying out GraphQL on OpenLiberty!")
}
----

You receive a response containing the boolean `true` to let you know that the request was successfully processed.
You can see the note that you added by running the following query operation.

[role='command']
----
query {
  system {
    note
  }
}
----

The response is similar to the following example:

[role='no_copy']
----
{
  "data": {
    "system": {
      "note": "I'm trying out GraphQL on OpenLiberty!"
    }
  }
}
----

Notice that only the `note` property is returned, as it was the only property in the request. 

== Implementing a GraphQL client



== Running the GraphQL client



== Tearing down the environment

When you're finished with the `backend` and `system` services, 
stop them by pressing `CTRL+C` in their respective command line interfaces. 
Alternatively, from another command line interface, navigate to the `start` directory and run the following commands:

[role='command']
----
mvn -pl system liberty:stop
mvn -pl backend liberty:stop
----

== Great work! You're done!

You just created a basic GraphQL service using MicroProfile GraphQL in Open Liberty!

include::{common-includes}/attribution.adoc[]

// ------------ END ------------
