// Copyright (c) 2021 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:projectid: graphql-intro
:page-layout: guide-multipane
:page-duration: 25 minutes
:page-releasedate: 2021-01-21
:page-essential: false
:page-description: Learn how to create and test a GraphQL service using MicroProfile GraphQL and Open Liberty.
:page-tags: ['MicroProfile', 'Java EE', 'Jakarta EE']
:page-related-guides: ['rest-intro', 'jpa-intro', 'mongodb-intro']
:page-permalink: /guides/{projectid}
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/master
:source-highlighter: prettify
:page-seo-title: Implementing GraphQL using Microprofile GraphQL in Open Liberty
:page-seo-description: Learn how to create a basic application that implements the GraphQL query language using Open Liberty and Microprofile GraphQL
:guide-author: Open Liberty
= Creating and consuming a GraphQL microservice

[.hidden]
NOTE: This repository contains the guide documentation source. To view the guide in published form,
view it on the https://openliberty.io/guides/{projectid}.html[Open Liberty website].

Explore how to create a GraphQL service using Microprofile GraphQL on Open Liberty

== What you'll learn

You will learn how to build and test a simple GraphQL service with Microprofile GraphQL. 
The service will respond to `POST` requests made to the `http://localhost:9080/graphql` URL. 
The `POST` requests will contain descriptions of operations that the user will want to execute.
If a query operation is made, GraphQL will respond with the desired resource and only the properties listed. 

This is beneficial when dealing with large resources or ones that contain properties that are expensive to calculate. 
By returning only the requested properties, GraphQL reduces the size of the responses. 
For resources that contain properties that are expensive to calculate such as other nested resources, GraphQL reduces processing time by only calculating them if requested. 

Unlike REST services, all GraphQL requests go to the same endpoint. 
Requests are differentiated by the contents of the request rather than the endpoint, which can simplify your application. 

You can learn more about GraphQL at https://graphql.org/[their webpage^].

///////////////////////////
// Getting started
///////////////////////////

[role='command']
include::{common-includes}/gitclone.adoc[]

[role='command']
include::{common-includes}/twyb-intro.adoc[]

Included with the application is a service called GraphiQL. 
GraphiQL is a webpage served by the Open Liberty server and can be used to aid development and testing of the service.
GraphiQL allows you to easily make `POST` requests to the GraphQL service and see the responses.
In GraphiQL you only need to type the body of the `POST` request, which can simplify manual tests. 
You're also able to view a history of your previous requests and repeat any of them.

In GraphiQL you'll also be able to view the application's documentation by clicking `Docs`. 
The documentation will describe the GraphQL schema.
The schema gives details on the various operations available and descriptions of them. 
If any data types are mentioned, you'll also be able to see descriptions of them and the fields contained within them if applicable. 

Run the following query operation in GraphiQL to get every property available. 

[role='command']
----
query {
  system {
    java {
      vendor
      version
    }
    operatingSystem {
      arch
      version
      name
    }
    username
    timezone
  }
}
----

The output will be similar to the following:

[role='no_copy']
----
{
  "data": {
    "system": {
      "java": {
        "vendor": "Oracle Corporation",
        "version": "13.0.2"
      },
      "operatingSystem": {
        "arch": "x86_64",
        "version": "10.15.6",
        "name": "Mac OS X"
      },
      "username": "admin",
      "timezone": "America/Toronto"
    }
  }
}
----

Run the following mutation operation to add a note to the system.

[role='command']
----
mutation {
  editNote(note: "I'm trying out GraphQL on OpenLiberty!")
}
----

You'll receive a response containing the boolean `true` to let you know that the request was successfully processed.
You can see the note you added by running the following query operation.

[role='command']
----
query {
  system {
    note
  }
}
----

The response will be similar to the following:

[role='no_copy']
----
{
  "data": {
    "system": {
      "note": "I'm trying out GraphQL on OpenLiberty!"
    }
  }
}
----

Notice that this time, only the `note` property is returned, as it was the only property in the request. 

[role='command']
include::{common-includes}/twyb-end.adoc[]

== Enabling GraphQL

Navigate to the `start` directory to begin.

[role="code_command hotspot file=0" ,subs="quotes"]
----
#Replace the `server.xml` file.#
`src/main/liberty/config/server.xml`
----

[role="code_command hotspot file=1" ,subs="quotes"]
----
#Replace the `pom.xml` file.#
`pom.xml`
----

Adding the [hotspot=graphql file=0]`mpGraphQL` feature to the [hotspot file=0]`server.xml` 
and the [hotspot=graphQLDependency file=1]`microprofile-graphql-api` dependency to the [hotspot file=1]`pom.xml` 
enables the GraphQL runtime and use of the GraphQL API for your application. 

// file 0
server.xml
[source, xml, linenums, role='code_column hide_tags=copyright']
----
include::finish/src/main/liberty/config/server.xml[]
----

// file 1
pom.xml
[source, xml, linenums, role='code_column hide_tags=copyright']
----
include::finish/pom.xml[]
----

== Creating GraphQL object types

Object types define the structure of the data that can be returned by GraphQL.
Object types are defined by annotated Java classes. 

[role="code_command hotspot file=0" ,subs="quotes"]
----
#Create the `JavaInfo.java` file.#
`src/main/java/io/openliberty/guides/graphql/models/JavaInfo.java`
----

The [hotspot file=0]`JavaInfo.java` file will define the `Java` object type in GraphQL.
This object type will describe information about the system's Java installation. 
The [hotspot=type file=0]`@Type` annotation maps the [hotspot file=0]`JavaInfo.java` file to defining the `Java` object type in GraphQL. 

The [hotspot=description file=0]`@Description` annotation gives a description to the `Java` object type in GraphQL.
This is what will appear in the schema and the documentation.  

The [hotspot=name1 hotspot=name2 file=0]`@Name` annotations map their respective properties to properties of the `Java` object type in GraphQL. 
Any of these properties can also be marked with the [hotspot=nonnull file=0]`@NonNull` annotation.
All data types in GraphQL are nullable by default.
The [hotspot=nonnull file=0]`@NonNull` annotation marks a property as non-nullable. 
The [hotspot=getVendor file=0]`getVendor()` and [hotspot=getVersion file=0]`getVersion()` getter functions will automatically be mapped to retrieve their respective properties in GraphQL. 

[role="code_command hotspot file=1" ,subs="quotes"]
----
#Create the `OperatingSystem.java` file.#
`src/main/java/io/openliberty/guides/graphql/models/OperatingSystem.java`
----
[role="code_command hotspot file=2" ,subs="quotes"]
----
#Create the `SystemInfo.java` file.#
`src/main/java/io/openliberty/guides/graphql/models/SystemInfo.java`
----

The [hotspot file=1]`OperatingSystem.java` and [hotspot file=2]`SystemInfo.java` files will be very similar to the [hotspot file=0]`JavaInfo.java` file.
[hotspot file=1]`OperatingSystem.java` will define the `OperatingSystem` object type in GraphQL to describe information about the operating system the application is running on. 
[hotspot file=2]`SystemInfo.java` will define the `System` object type in GraphQL to describe information about the operating system the application is running on. 

// file 0
JavaInfo.java
[source, java, linenums, role='code_column hide_tags=copyright']
----
include::finish/src/main/java/io/openliberty/guides/graphql/models/JavaInfo.java[]
----

// file 1
OperatingSystem.java
[source, java, linenums, role='code_column hide_tags=copyright']
----
include::finish/src/main/java/io/openliberty/guides/graphql/models/OperatingSystem.java[]
----

// file 2
SystemInfo.java
[source, java, linenums, role='code_column hide_tags=copyright']
----
include::finish/src/main/java/io/openliberty/guides/graphql/models/SystemInfo.java[]
----

== Implementing GraphQL resolvers

Resolvers are functions that will define what operations can be performed to retrieve or modify data. 

[role="code_command hotspot file=3" ,subs="quotes"]
----
#Create the `SystemResource.java` file.#
`src/main/java/io/openliberty/guides/graphql/SystemResource.java`
----

The resolvers are defined in the [hotspot file=3]`SystemResource.java` file.
The [hotspot=graphqlapi file=3]`@GraphQLApi` annotation makes it so that GraphQL will use the methods defined in this class as resolvers. 

The [hotspot=query file=3]`@Query` annotation maps the [hotspot=getSystemInfo file=3]`getSystemInfo()` function to handling `system` requests. 

The [hotspot=mutation file=3]`@Mutation` annotation maps the [hotspot=editNoteFunction file=3]`editNote()` function to handling `editNote` requests. 
The [hotspot=editNoteHeader file=3]`@Name` annotation in this context denotes inputs for the mutation request. 
Here the input will determine a note to write into the system properties. 

Each resolver function has an [hotspot=description1 hotspot=description2 file=3]`@Description` annotation, which gives the description to be used for the schema. 

The [hotspot=operatingSystemHeader hotspot=javaHeader file=3]`@Source` annotation is used to add properties to object types. 
Here it adds [hotspot=javaFunction file=3]`JavaInfo` and [hotspot=os file=3]`OperatingSystem` objects as properties 
to the `SystemInfo` object that is returned for the `system` request defined earlier by the [hotspot=getSystemInfo file=3]`getSystemInfo()` function.
The [hotspot=operatingSystemHeader hotspot=javaHeader file=3]`@Source` annotation is used for any properties that are expensive to calculate or look up.
These properties will only be calculated or looked up if requested, saving server time and resources. 
Here it's used for the [hotspot=javaFunction file=3]`JavaInfo` and [hotspot=os file=3]`OperatingSystem` object types. 

// file 3
SystemResource.java
[source, java, linenums, role='code_column hide_tags=copyright']
----
include::finish/src/main/java/io/openliberty/guides/graphql/SystemResource.java[]
----

== Running the application

Run the following commands to package and start the application.

[role='command']
----
mvn liberty:run
----

GraphiQL has been set up and included for you.
Access GraphiQL at the http://localhost:9080/graphiql.html[^] URL.
Queries made through GraphiQL will be the same as queries made through `POST` requests. 

Your schema will be visible at the http://localhost:9080/graphql/schema.graphql[^] URL. 

After you have finished trying your application, stop it by pressing `CTRL+C` in the command-line session where you ran the server. 
Alternatively, run the following command in the `finish` directory in another command-line-session.

[role='command']
----
mvn liberty:stop
----

== Testing the application

Manual tests can be done using GraphiQL at the http://localhost:9080/graphiql.html[^] URL. 
However, automated tests are a better approach because they trigger a failure if a change introduces a bug.

We'll write tests using JUnit to call the application server directly. 

[role="code_command hotspot file=0" ,subs="quotes"]
----
#Create the `SystemIT.java` file.#
`src/test/java/io/openliberty/guides/graphql/SystemIT.java`
----

The [hotspot file=0]`SystemIT` class contains our test methods.

Each test is annotated with the [hotspot=test1 hotspot=test2 file=0]`@Test` annotation. 

The [hotspot=testGet file=0]`testGetSystem()` method makes a query using the `system` resolver through a `POST` request.
It then verifies that the response is not empty and that it's free of errors. 

The [hotspot=testEdit file=0]`testEditNote()` method makes a query using the `editNote` resolver.
It will try to set the note to be the current system time. 
Then, it makes a query using the `system` resolver to ensure the note was saved correctly. 

// file 0
SystemIT.java
[source, java, linenums, role='code_column hide_tags=copyright']
----
include::finish/src/test/java/io/openliberty/guides/graphql/SystemIT.java[]
----

=== Running the tests

Use the provided `testApp.sh` script to rebuild and test your application.

[role='command']
----
../scripts/testApp.sh
----

You will see the following output:

[source,role="no_copy"]
----
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.008 s - in io.openliberty.guides.graphql.SystemIT

Results:

Tests run: 2, Failures: 0, Errors: 0, Skipped: 0
----

// file 0
SystemIT.java
[source, java, linenums, role='code_column hide_tags=copyright']
----
include::finish/src/test/java/io/openliberty/guides/graphql/SystemIT.java[]
----

== Great work! You're done!

You just created a basic GraphQL service using Microprofile GraphQL in Open Liberty!

include::{common-includes}/attribution.adoc[]

// ------------ END ------------
