// Copyright (c) 2021 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:projectid: graphql-intro
:page-layout: guide-multipane
:page-duration: 25 minutes
:page-releasedate: 2021-04-28
:page-essential: false
:page-description: Learn how to create and test a GraphQL service using MicroProfile GraphQL and Open Liberty.
:page-tags: ['MicroProfile', 'Jakarta EE']
:page-related-guides: ['rest-intro', 'jpa-intro', 'mongodb-intro']
:page-permalink: /guides/{projectid}
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/master
:source-highlighter: prettify
:page-seo-title: Accessing and manipulating data using MicroProfile GraphQL in Open Liberty
:page-seo-description: Learn how to create an application that manipulates and returns data using the GraphQL query language implemented through MicroProfile GraphQL
:guide-author: Open Liberty
= Accessing and manipulating data with GraphQL

[.hidden]
NOTE: This repository contains the guide documentation source. To view the guide in published form,
view it on the https://openliberty.io/guides/{projectid}.html[Open Liberty website].

Explore how to use GraphQL to access and manipulate data using MicroProfile GraphQL on Open Liberty

== What you'll learn

You will learn how to build and test a simple GraphQL service with MicroProfile GraphQL. 

GraphQL is an open source data query language. 
Unlike REST APIs, each `POST` request that is sent to a GraphQL service goes to a single HTTP endpoint.
Create, read, update, and delete (CRUD) operations and their details are differentiated by the contents of the request.
If the operation returns data, the user specifies what properties of the data that they want returned. 
For read operations, a JSON object is returned that contains only the data and properties that are specified.
For other operations, a JSON object might be returned containing information such as a success message. 

The returning of only the specified properties in a read operation is beneficial when you deal 
with large resources or resources that contain properties that are expensive to calculate. 
By returning only the requested properties, GraphQL reduces the size of the responses. 
For resources that contain properties that are expensive to calculate, such as other nested resources, 
GraphQL reduces processing time by calculating them only if requested. 

You can learn more about GraphQL at the https://graphql.org/[GraphQL website^].

You will start with a service that responds to `GET` requests at the `\http://localhost:9080/system/properties` URL
with all of your system information. 
This service will be modified to respond to `POST` requests that are made to the `\http://localhost:9080/graphql` URL. 
It will allow for two basic GraphQL operations - a `query` operation and a `mutation` operation.

The `query` operation type in GraphQL is a read-only operation.
In this guide it will be used to retrieve the system information.
The `mutation` operation type in GraphQL can be used for create, update, or delete operations. 
In this guide it will be used to save a note of your choice into the system information.

Manual testing of the application can be done by using 
https://github.com/graphql/graphiql/tree/main/packages/graphiql[GraphiQL^], which is included in the project for you. 
GraphiQL is a webpage that allows you to easily make requests to the GraphQL service and see the responses.
In GraphiQL you need to type only the body of the request, which streamlines manual tests.
You're also able to view a history of your previous requests and repeat any of them.

///////////////////////////
// Getting started
///////////////////////////

[role='command']
include::{common-includes}/gitclone.adoc[]

///////////////////////////
// Try what you'll build
///////////////////////////
[role='command']
include::{common-includes}/twyb-intro.adoc[]

Access the application through GraphiQL at the http://localhost:9080/graphiql.html[^] URL.

Enter the following `query` operation into the input box. 

[role='command']
----
query {
  system {
    username
  }
}
----

Press `CTRL+enter` to run your `query` operation and generate output that is similar to the following example:

[role='no_copy']
----
{
  "data": {
    "system": {
      "username": "admin"
    }
  }
}
----

[role='command']
include::{common-includes}/twyb-end.adoc[]

== Creating GraphQL object types

Navigate to the `start` directory to begin.

[role='command']
include::{common-includes}/devmode-lmp33-start.adoc[]

Object types define the structure of the data returned by GraphQL. 
Annotations that are applied to the declaration and properties of Java classes define object types.

[role="code_command hotspot file=0", subs="quotes"]
----
#Create the `JavaInfo` class.#
`src/main/java/io/openliberty/guides/graphql/models/JavaInfo.java`
----

The [hotspot=class file=0]`JavaInfo` class is annotated with an `@Type` annotation. 
The [hotspot=type file=0]`@Type("java")` annotation maps this class to define the `java` object type in GraphQL.
The `java` object type gives information on the Java installation of the system. 

The [hotspot=description file=0]`@Description` annotation gives a description to the `java` object type in GraphQL.
This description is what appears in the schema and the documentation. 
Descriptions aren't required, but it's good practice to include them. 

The [hotspot=name file=0]`@Name` annotation maps the `vendor` property to the `vendorName` property of the `java` object type in GraphQL. 
The [hotspot=name file=0]`@Name` annotation is used when mapping a property in a Java object to a property of a different name in the GraphQL object type.
Without an [hotspot=name file=0]`@Name` annotation, the Java object property is automatically 
mapped to a GraphQL object type property of the same name. 

All data types in GraphQL are nullable by default.
Non-nullable properties are annotated with the [hotspot=nonnull file=0]`@NonNull` annotation.
The [hotspot=getVendor file=0]`getVendor()` and [hotspot=getVersion file=0]`getVersion()` getter functions 
are automatically mapped to retrieve their respective properties in GraphQL. 
If needed, setter functions are also supported and automatically mapped. 

[role="code_command hotspot file=1" ,subs="quotes"]
----
#Create the `OperatingSystem` class.#
`src/main/java/io/openliberty/guides/graphql/models/OperatingSystem.java`
----

The [hotspot=class file=1]`OperatingSystem` class is set up similarly.
It maps to the [hotspot=type file=1]`operatingSystem` object type, which describes the operating system's information. 

[role="code_command hotspot file=2" ,subs="quotes"]
----
#Create the `SystemInfo` class.#
`src/main/java/io/openliberty/guides/graphql/models/SystemInfo.java`
----

The [hotspot=class file=2]`SystemInfo` class is similar to the previous two files. 
It maps to the [hotspot=type file=2]`system` object type, which describes other information Java can retrieve from the system properties.

The `java` and `operatingSystem` object types are used as nested objects within the `system` object type.
However, nested objects and other properties that are expensive to calculate or retrieve are not included in the class of an object type.
Instead, expensive properties are added as part of implementing GraphQL resolvers. 

// file 0
JavaInfo.java
[source, java, linenums, role='code_column hide_tags=copyright']
----
include::finish/src/main/java/io/openliberty/guides/graphql/models/JavaInfo.java[]
----

// file 1
OperatingSystem.java
[source, java, linenums, role='code_column hide_tags=copyright']
----
include::finish/src/main/java/io/openliberty/guides/graphql/models/OperatingSystem.java[]
----

// file 2
SystemInfo.java
[source, java, linenums, role='code_column hide_tags=copyright']
----
include::finish/src/main/java/io/openliberty/guides/graphql/models/SystemInfo.java[]
----

== Implementing GraphQL resolvers

Resolvers are functions that provide instructions for GraphQL operations.
Each operation requires a corresponding resolver.
The `query` operation type is read-only and fetches data.
The `mutation` operation type can create, delete, or modify data. 

[role="code_command hotspot file=0" ,subs="quotes"]
----
#Create the `GraphQLEndpoint` class.#
`src/main/java/io/openliberty/guides/graphql/GraphQLEndpoint.java`
----

The resolvers are defined in the [hotspot file=0]`GraphQLEndpoint.java` file.
The [hotspot=graphqlapi file=0]`@GraphQLApi` annotation enables GraphQL to use the methods that are defined in this class as resolvers. 

The [hotspot=query file=0]`@Query` annotation maps functions to operations of the `query` type.
This annotation maps the [hotspot=getSystemInfo file=0]`getSystemInfo()` function to handling `system` requests which retrieves the system information. 

The [hotspot=mutation file=0]`@Mutation` annotation maps functions to operations of the `mutation` type.
This annotation maps the [hotspot=editNoteFunction file=0]`editNote()` function to handling `editNote` operations. 
The [hotspot=editNoteHeader file=0]`@Name` annotation in this context denotes what inputs are used for the operation.
Within the [hotspot=editNoteHeader file=0]`@Name` annotation, the `note` input specifies the note that is written into the system properties.

Each resolver function has an [hotspot=description1 hotspot=description2 file=0]`@Description` annotation, 
which provides a description to be used for the schema. 
Descriptions aren't required, but it's good practice to include. 

The [hotspot=operatingSystemHeader hotspot=javaHeader file=0]`@Source` annotation is used to add properties to object types. 
This annotation adds [hotspot=javaFunction file=0]`java` 
and [hotspot=os file=0]`operatingSystem` object types as properties of the `system` object type.
The [hotspot=operatingSystemHeader hotspot=javaHeader file=0]`@Source` annotation is used for any properties that are expensive to calculate or search for.
These properties are calculated or searched for only if requested, which saves time and resources.

// file 0
GraphQLEndpoint.java
[source, java, linenums, role='code_column hide_tags=copyright']
----
include::finish/src/main/java/io/openliberty/guides/graphql/GraphQLEndpoint.java[]
----

== Enabling GraphQL

To use GraphQL, the MicroProfile GraphQL dependencies and features need to be included. 

[role="code_command hotspot file=0" ,subs="quotes"]
----
#Replace the Maven project file.#
`pom.xml`
----

Adding the [hotspot=graphQLDependency file=0]`microprofile-graphql-api` dependency to the [hotspot file=0]`pom.xml` 
enables the GraphQL annotations that are used to develop the application. 

The Open Liberty server needs to be configured to support the GraphQL query language. 

[role="code_command hotspot file=1" ,subs="quotes"]
----
#Replace the server configuration file.#
`src/main/liberty/config/server.xml`
----

The https://openliberty.io/docs/20.0.0.12/reference/feature/mpGraphQL-1.0.html[MicroProfile GraphQL^] ([hotspot=graphql file=1]`mpGraphQL-1.0`) feature
that is added to the [hotspot file=1]`server.xml` enables the use of the GraphQL feature in OpenLiberty.

// file 0
pom.xml
[source, xml, linenums, role='code_column hide_tags=copyright']
----
include::finish/pom.xml[]
----

// file 1
server.xml
[source, xml, linenums, role='code_column hide_tags=copyright']
----
include::finish/src/main/liberty/config/server.xml[]
----

///////////////////////////
// Running the application
///////////////////////////

[role='command']
include::{common-includes}/devmode-build.adoc[]

GraphiQL has already been set up and included for you.
Access GraphiQL at the http://localhost:9080/graphiql.html[^] URL.
Queries that are made through GraphiQL are the same as queries that are made through HTTP requests. 

In GraphiQL, you can view the application documentation by clicking the `Docs` button on the menu bar. 
The documentation describes the GraphQL schema.
The schema gives details on the various operations that are available. 
If any data types are mentioned, you can also see descriptions of them and the fields that are contained within them if applicable. 
The schema is also visible at the http://localhost:9080/graphql/schema.graphql[^] URL. 

Run the following `query` operation in GraphiQL to get every system property. 

[role='command']
----
query {
  system {
    java { vendorName version }
    operatingSystem { arch version name }
    username
    timezone
  }
}
----

The output is similar to the following example:

[role='no_copy']
----
{
  "data": {
    "system": {
      "java": {
        "vendorName": "N/A",
        "version": "13.0.2"
      },
      "operatingSystem": {
        "arch": "x86_64",
        "version": "10.15.7",
        "name": "Mac OS X"
      },
      "username": "admin",
      "timezone": "America/Toronto"
    }
  }
}
----
Run the following mutation operation to add a note to the system.

[role='command']
----
mutation {
  editNote(note: "I'm trying out GraphQL on OpenLiberty!")
}
----

You receive a response containing the boolean `true` to let you know that the request was successfully processed.
You can see the note that you added by running the following query operation.

[role='command']
----
query {
  system {
    note
  }
}
----

The response is similar to the following example:

[role='no_copy']
----
{
  "data": {
    "system": {
      "note": "I'm trying out GraphQL on OpenLiberty!"
    }
  }
}
----

Notice that only the `note` property is returned, as it was the only property in the request. 

== Testing the application

Manual tests can be done by using GraphiQL at the http://localhost:9080/graphiql.html[^] URL. 
However, automated tests are a better approach because they trigger a failure if a change introduces a bug.

You can write tests by using JUnit to call the application server directly. 

[role="code_command hotspot file=0" ,subs="quotes"]
----
#Create the `SystemIT` class.#
`src/test/java/io/openliberty/guides/graphql/SystemIT.java`
----

The [hotspot file=0]`SystemIT` class contains the test methods.

Each test is annotated with the [hotspot=test1 hotspot=test2 file=0]`@Test` annotation. 

The [hotspot=testGet file=0]`testGetSystem()` method makes a query using the `system` resolver through a `POST` request.
JSON-B is used to parse the responses into Java objects.
The test verifies that the response contains data, is responding to the correct operation, and is free of errors. 
Then it checks the `username` property to ensure it is returned correctly.

The [hotspot=testEdit file=0]`testEditNote()` method makes a query using the `editNote` resolver.
It will try to set the note to be the current system time and ensures the response says there were no problems with the operation.
Then, it makes a query using the `system` resolver to ensure the note was saved correctly. 

// file 0
SystemIT.java
[source, java, linenums, role='code_column hide_tags=copyright']
----
include::finish/src/test/java/io/openliberty/guides/graphql/SystemIT.java[]
----

// Running the tests

[role=command]
include::{common-includes}/devmode-test.adoc[]

The tests show output similar to the following: 

[source,role="no_copy"]
----
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.008 s - in io.openliberty.guides.graphql.SystemIT

Results:

Tests run: 2, Failures: 0, Errors: 0, Skipped: 0
----

[role=command]
include::{common-includes}/devmode-quit.adoc[]

== Great work! You're done!

You just created a basic GraphQL service using MicroProfile GraphQL in Open Liberty!

include::{common-includes}/attribution.adoc[]

// ------------ END ------------
