// Copyright (c) 2020 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:projectid: graphql-intro
:page-layout: guide-multipane
:page-duration: 25 minutes
:page-releasedate: 2020-12-21
:page-essential: false
:page-description: Learn how to create and test a GraphQL service using MicroProfile GraphQL and Open Liberty.
:page-tags: ['MicroProfile', 'Java EE', 'Jakarta EE']
:page-related-guides: ['rest-intro']
:page-permalink: /guides/{projectid}
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/master
:source-highlighter: prettify
:page-seo-title: Creating a GraphQL service using Microprofile GraphQL
:page-seo-description: Find out how to create and test a GraphQL service on Open Liberty using Microprofile GraphQL
:guide-author: Open Liberty
= Creating and consuming a GraphQL microservice

[.hidden]
NOTE: This repository contains the guide documentation source. To view the guide in published form,
view it on the https://openliberty.io/guides/{projectid}.html[Open Liberty website].

Explore how to create a GraphQL service using Microprofile GraphQL on Open Liberty

== What you'll learn

You will learn how to build and test a simple GraphQL service with Microprofile GraphQL. 
The service will respond to `POST` requests made to the `http://localhost:9080/graphql` URL. 
The `POST` requests will contain a query with a requested object and a list of fields within that object.
GraphQL will respond with the desired object and only the fields listed. 

This is beneficial when dealing with large objects or objects which contain fields that are expensive to calculate. 
By returning only the requested fields, GraphQL reduces the size of the responses. 
For objects that contain fields that are expensive to calculate such as other nested objects, GraphQL reduces processing time by only calculating them if requested. 

Unlike REST services, all GraphQL requests go to the same endpoint. 
Requests are differentiated by the contents of the request, which can simplify your application. 

You can learn more about GraphQL by visiting https://graphql.org/[their webpage^].

///////////////////////////
// Getting started
///////////////////////////

[role='command']
include::{common-includes}/gitclone.adoc[]

[role='command']
include::{common-includes}/twyb-intro.adoc[]

The application contains a service called GraphiQL. 
GraphiQL is a webpage served by the Open Liberty server and can be used to assist in development and testing of the service.
GraphiQL allows you to easily make `POST` requests to the service and see the responses.

Once the server is running, access the schema at the http://localhost:9080/graphql/schema.graphql[^] URL. 
The schema informs you of the queries available in the service as well as the possible objects that can be returned. 
Open GraphiQL at the http://localhost:9080/graphiql.html[^] URL. 
Run the following `query` command in GraphiQL to get every property available. 

[role='command']
----
query {
  system {
    java {
      vendor
      version
    }
    operatingSystem {
      arch
      version
      name
    }
    username
    timezone
  }
}
----

The output will be similar to the following:

[role='no_copy']
----
{
  "data": {
    "system": {
      "java": {
        "vendor": "Oracle Corporation",
        "version": "13.0.2"
      },
      "operatingSystem": {
        "arch": "x86_64",
        "version": "10.15.6",
        "name": "Mac OS X"
      },
      "username": "admin",
      "timezone": "America/Toronto"
    }
  }
}
----

Run the following `mutation` command to add a note to the system.

[role='command']
----
mutation {
  editNote(note:"I am trying out GraphQL on OpenLiberty!")
}
----

You will receive a response containing the boolean `true` to notify you that the request was processed.
You can see the note you added by running the following query.

[role='command']
----
query {
  system {
    note
  }
}
----

The response will be similar to the following:

[role='no_copy']
----
{
  "data": {
    "system": {
      "note": "I am trying out GraphQL on OpenLiberty!"
    }
  }
}
----

Notice that this time, only the `note` property is returned, as it was the only field in the `query` request. 

[role='command']
include::{common-includes}/twyb-end.adoc[]

== Building the application

Navigate to the `start` directory

[role='command']
include::{common-includes}/devmode-start.adoc[]

== Enabling GraphQL

[role="code_command hotspot" ,subs="quotes"]
----
#Replace the `server.xml` file.#
`finish/src/main/liberty/config/server.xml`
----

Adding the [hotspot=graphql]`mpGraphQL` feature enables the GraphQL runtime and use of GraphQL API for your application.

SystemApplication.java
[source, xml, linenums, role='code_column hide_tags=comment']
----
include::finish/src/main/liberty/config/server.xml[]
----

== Creating the GraphQL API


== Great work! You're done!

You just created a basic GraphQL service using Microprofile GraphQL in Open Liberty!

include::{common-includes}/attribution.adoc[]

// ------------ END ------------