// Copyright (c) 2021 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:projectid: graphql-intro
:page-layout: guide-multipane
:page-duration: 25 minutes
:page-releasedate: 2021-01-21
:page-essential: false
:page-description: Learn how to create and test a GraphQL service using MicroProfile GraphQL and Open Liberty.
:page-tags: ['MicroProfile', 'Java EE', 'Jakarta EE']
:page-related-guides: ['rest-intro', 'jpa-intro', 'mongodb-intro']
:page-permalink: /guides/{projectid}
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/master
:source-highlighter: prettify
:page-seo-title: Accessing and manipulating data using Microprofile GraphQL in Open Liberty
:page-seo-description: Learn how to create an application that manipulates and returns data using the GraphQL query language implemented through Microprofile GraphQL
:guide-author: Open Liberty
= Accessing and manipulating data with GraphQL

[.hidden]
NOTE: This repository contains the guide documentation source. To view the guide in published form,
view it on the https://openliberty.io/guides/{projectid}.html[Open Liberty website].

Explore how to use GraphQL to access and manipulate data using Microprofile GraphQL on Open Liberty

== What you'll learn

You will learn how to build and test a simple GraphQL service with Microprofile GraphQL. 

GraphQL is an open-source data query and manipulation language. 
GraphQL responds to `POST` requests made to a single endpoint. 
Each request contains descriptions of the operation the user will want to execute.
If the operation returns data, the user will also specify what properties of the data they want returned. 
All data is returned as a JSON object. 

This is beneficial when dealing with large resources or ones that contain properties that are expensive to calculate. 
By returning only the requested properties, GraphQL reduces the size of the responses. 
For resources that contain properties that are expensive to calculate such as other nested resources, GraphQL reduces processing time by only calculating them if requested. 

You can learn more about GraphQL at https://graphql.org/[the GraphQL website^].

The service you will create will respond to `POST` requests made to the `http://localhost:9080/graphql` URL. 
The operations you will implement will be a simple `query` operation and a `mutation` operation.
The `query` operation will return system information.
The `mutation` operation will save a note of your choice into the system information. 

Included with the application is a service called GraphiQL. 
GraphiQL is a webpage served by the Open Liberty server and can be used to aid development and testing of the service.
GraphiQL allows you to easily make `POST` requests to the GraphQL service and see the responses.
In GraphiQL you only need to type the body of the `POST` request, which can simplify manual tests. 
You're also able to view a history of your previous requests and repeat any of them.

///////////////////////////
// Getting started
///////////////////////////

[role='command']
include::{common-includes}/gitclone.adoc[]

// No try what you'll build, examples and explanations later in guide

== Creating GraphQL object types

Navigate to the `start` directory to begin.

[role='command']
include::{common-includes}/devmode-lmp33-start.adoc[]

[role="code_command hotspot file=1" ,subs="quotes"]
----
#Replace the Maven project file.#
`pom.xml`
----

Adding the [hotspot=graphQLDependency file=1]`microprofile-graphql-api` dependency to the [hotspot file=1]`pom.xml` 
enables the use of the GraphQL annotations to develop the application. 

These annotations are used in Java classes to define the object types of our application.
Object types define the structure of the data that can be returned by GraphQL. 

[role="code_command hotspot file=1", subs="quotes"]
----
#Create the `JavaInfo` class.#
`src/main/java/io/openliberty/guides/graphql/models/JavaInfo.java`
----

The [hotspot file=1]`JavaInfo.java` file will define the `Java` object type in GraphQL.
This object type will describe information about the system's Java installation. 
The [hotspot=type file=1]`@Type` annotation maps the [hotspot file=1]`JavaInfo.java` file to defining the `Java` object type in GraphQL. 

The [hotspot=description file=1]`@Description` annotation gives a description to the `Java` object type in GraphQL.
This is what will appear in the schema and the documentation.  

The [hotspot=name1 hotspot=name2 file=1]`@Name` annotations map their respective properties to properties of the `Java` object type in GraphQL. 
Any of these properties can also be marked with the [hotspot=nonnull file=1]`@NonNull` annotation.
All data types in GraphQL are nullable by default.
The [hotspot=nonnull file=1]`@NonNull` annotation marks a property as non-nullable. 
The [hotspot=getVendor file=1]`getVendor()` and [hotspot=getVersion file=1]`getVersion()` getter functions will automatically be mapped to retrieve their respective properties in GraphQL. 

[role="code_command hotspot file=2" ,subs="quotes"]
----
#Create the `OperatingSystem` class.#
`src/main/java/io/openliberty/guides/graphql/models/OperatingSystem.java`
----

The [hotspot file=2]`OperatingSystem.java` file will be set up similarly.
It will describe the operating system running on the machine the application is running on. 

[role="code_command hotspot file=3" ,subs="quotes"]
----
#Create the `SystemInfo` class.#
`src/main/java/io/openliberty/guides/graphql/models/SystemInfo.java`
----

The [hotspot file=3]`SystemInfo.java` file is similar to the previous two files. 
It will describe overall information about the machine the application is running on.
This object type will include the [hotspot file=2]`OperatingSystem` and [hotspot file=1]`JavaInfo` objects as nested objects.
However, these object types are not included here.
They will instead be added as part of implementing the resolver functions.

// file 0
pom.xml
[source, xml, linenums, role='code_column hide_tags=copyright']
----
include::finish/pom.xml[]
----

// file 1
JavaInfo.java
[source, java, linenums, role='code_column hide_tags=copyright']
----
include::finish/src/main/java/io/openliberty/guides/graphql/models/JavaInfo.java[]
----

// file 2
OperatingSystem.java
[source, java, linenums, role='code_column hide_tags=copyright']
----
include::finish/src/main/java/io/openliberty/guides/graphql/models/OperatingSystem.java[]
----

// file 3
SystemInfo.java
[source, java, linenums, role='code_column hide_tags=copyright']
----
include::finish/src/main/java/io/openliberty/guides/graphql/models/SystemInfo.java[]
----

== Implementing GraphQL resolvers

Resolvers are functions that will define what operations can be performed to retrieve or modify data. 

[role="code_command hotspot file=0" ,subs="quotes"]
----
#Create the `SystemResource` class.#
`src/main/java/io/openliberty/guides/graphql/SystemResource.java`
----

The resolvers are defined in the [hotspot file=0]`SystemResource.java` file.
The [hotspot=graphqlapi file=0]`@GraphQLApi` annotation makes it so that GraphQL will use the methods defined in this class as resolvers. 

The [hotspot=query file=0]`@Query` annotation maps the [hotspot=getSystemInfo file=0]`getSystemInfo()` function to handling `system` requests. 

The [hotspot=mutation file=0]`@Mutation` annotation maps the [hotspot=editNoteFunction file=0]`editNote()` function to handling `editNote` requests. 
The [hotspot=editNoteHeader file=0]`@Name` annotation in this context denotes inputs for the mutation request. 
Here the input will determine a note to write into the system properties. 

Each resolver function has an [hotspot=description1 hotspot=description2 file=0]`@Description` annotation, which gives the description to be used for the schema. 

The [hotspot=operatingSystemHeader hotspot=javaHeader file=0]`@Source` annotation is used to add properties to object types. 
Here it adds [hotspot=javaFunction file=0]`JavaInfo` and [hotspot=os file=0]`OperatingSystem` objects as properties 
to the `SystemInfo` object that is returned for the `system` request defined earlier by the [hotspot=getSystemInfo file=0]`getSystemInfo()` function.
The [hotspot=operatingSystemHeader hotspot=javaHeader file=0]`@Source` annotation is used for any properties that are expensive to calculate or look up.
These properties will only be calculated or looked up if requested, saving server time and resources. 
Here it's used to add the [hotspot=javaFunction file=0]`JavaInfo` and [hotspot=os file=0]`OperatingSystem` object types as nested objects. 

// file 0
SystemResource.java
[source, java, linenums, role='code_column hide_tags=copyright']
----
include::finish/src/main/java/io/openliberty/guides/graphql/SystemResource.java[]
----

== Enabling GraphQL


[role="code_command hotspot file=0" ,subs="quotes"]
----
#Replace the server configuration file.#
`src/main/liberty/config/server.xml`
----

Finally, adding the [hotspot=graphql file=0]`mpGraphQL` feature to the [hotspot file=0]`server.xml` enables the use of the GraphQL feature in OpenLiberty.

// file 0
server.xml
[source, xml, linenums, role='code_column hide_tags=copyright']
----
include::finish/src/main/liberty/config/server.xml[]
----

== Running the application

Because you started Open Liberty in dev mode, type `r` and press the `enter/return` key to restart the application.

GraphiQL has already been set up and included for you.
Access GraphiQL at the http://localhost:9080/graphiql.html[^] URL.
Queries made through GraphiQL will be the same as queries made through `POST` requests. 

In GraphiQL you can view the application documentation by clicking `Docs`. 
The documentation will describe the GraphQL schema.
The schema gives details on the various operations available and descriptions of them. 
If any data types are mentioned, you'll also be able to see descriptions of them and the fields contained within them if applicable. 
The schema will also be visible at the http://localhost:9080/graphql/schema.graphql[^] URL. 

Run the following `query` operation to get every system property by entering it into GraphiQL. 

[role='command']
----
query {
  system {
    java {
      vendor
      version
    }
    operatingSystem {
      arch
      version
      name
    }
    username
    timezone
  }
}
----

The output will be similar to the following:

[role='no_copy']
----
{
  "data": {
    "system": {
      "java": {
        "vendor": "Oracle Corporation",
        "version": "11.0.7"
      },
      "operatingSystem": {
        "arch": "x86_64",
        "version": "10.15.6",
        "name": "Mac OS X"
      },
      "username": "admin",
      "timezone": "America/Toronto"
    }
  }
}
----
Run the following mutation operation to add a note to the system.

[role='command']
----
mutation {
  editNote(note: "I'm trying out GraphQL on OpenLiberty!")
}
----

You'll receive a response containing the boolean `true` to let you know that the request was successfully processed.
You can see the note you added by running the following query operation.

[role='command']
----
query {
  system {
    note
  }
}
----

The response will be similar to the following:

[role='no_copy']
----
{
  "data": {
    "system": {
      "note": "I'm trying out GraphQL on OpenLiberty!"
    }
  }
}
----

Notice that this time, only the `note` property is returned, as it was the only property in the request. 

After you have finished trying your application, stop it by pressing `CTRL+C` in the command-line session where you ran the server. 
Alternatively, run the following command in the `start` directory in another command-line-session.

[role='command']
----
mvn liberty:stop
----

== Testing the application

Manual tests can be done using GraphiQL at the http://localhost:9080/graphiql.html[^] URL. 
However, automated tests are a better approach because they trigger a failure if a change introduces a bug.

We'll write tests using JUnit to call the application server directly. 

[role="code_command hotspot file=0" ,subs="quotes"]
----
#Create the `SystemIT` class.#
`src/test/java/io/openliberty/guides/graphql/SystemIT.java`
----

The [hotspot file=0]`SystemIT` class contains our test methods.

Each test is annotated with the [hotspot=test1 hotspot=test2 file=0]`@Test` annotation. 

The [hotspot=testGet file=0]`testGetSystem()` method makes a query using the `system` resolver through a `POST` request.
It then verifies that the response is not empty and that it's free of errors. 

The [hotspot=testEdit file=0]`testEditNote()` method makes a query using the `editNote` resolver.
It will try to set the note to be the current system time. 
Then, it makes a query using the `system` resolver to ensure the note was saved correctly. 

// file 0
SystemIT.java
[source, java, linenums, role='code_column hide_tags=copyright']
----
include::finish/src/test/java/io/openliberty/guides/graphql/SystemIT.java[]
----

// Running the tests

[role=command]
include::{common-includes}/devmode-test.adoc[]

You will see the following output:

[source,role="no_copy"]
----
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.008 s - in io.openliberty.guides.graphql.SystemIT

Results:

Tests run: 2, Failures: 0, Errors: 0, Skipped: 0
----

[role=command]
include::{common-includes}/devmode-quit.adoc[]

== Great work! You're done!

You just created a basic GraphQL service using Microprofile GraphQL in Open Liberty!

include::{common-includes}/attribution.adoc[]

// ------------ END ------------
